/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness: the process is up.
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ready
         * @description Readiness: the database answers, a model is loaded and the business rules are read.
         *
         *     A model activated or rules put in place after startup are picked up here, so a stack
         *     seeded while running becomes ready without a restart.
         */
        get: operations["ready_api_v1_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description OAuth2 password flow for API clients: `username` is the user's email. The token comes
         *     back in the body; send it as `Authorization: Bearer <token>`.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current Session
         * @description Who is signed in, and when the session ends.
         */
        get: operations["current_session_api_v1_auth_session_get"];
        put?: never;
        /**
         * Start Session
         * @description Sign in for the dashboard. The token goes into an HttpOnly cookie that page scripts
         *     cannot read, instead of the body. Needs the X-Requested-With header.
         */
        post: operations["start_session_api_v1_auth_session_post"];
        /**
         * End Session
         * @description Sign out: the browser drops the session cookie. Needs the X-Requested-With header.
         */
        delete: operations["end_session_api_v1_auth_session_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_v1_users_get"];
        put?: never;
        /** Create User */
        post: operations["create_user_api_v1_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update User */
        patch: operations["update_user_api_v1_users__user_id__patch"];
        trace?: never;
    };
    "/api/v1/predictions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Score Transaction
         * @description Score one transaction and store it with its risk assessment.
         *
         *     Send one system's record, plus the other systems' records of the same transaction when
         *     known. Records for a TransactionID that is already stored are added to it (409 if that
         *     system's record is already there) and the transaction is re-scored.
         */
        post: operations["score_transaction_api_v1_predictions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/predictions/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Score Batch
         * @description Score several transactions; each succeeds or fails on its own. Each one counts
         *     against the scoring rate limit.
         */
        post: operations["score_batch_api_v1_predictions_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/predictions/{prediction_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Prediction */
        get: operations["get_prediction_api_v1_predictions__prediction_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Transactions
         * @description Stored transactions with their latest score. `sort` takes comma-separated fields
         *     (priority, risk_score, transaction_date, amount, exposure_usd, scored_at, transaction_id),
         *     each optionally prefixed with '-' for descending order.
         */
        get: operations["list_transactions_api_v1_transactions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions/{transaction_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Transaction
         * @description GL, MA and FA records side by side, with prediction history and reviews.
         */
        get: operations["get_transaction_api_v1_transactions__transaction_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingestion/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Month
         * @description Load a month: GL, FA and join map files, plus MA as a file or from its REST API.
         *
         *     Returns at once with a queued batch; poll GET /ingestion/batches/{id} for the outcome.
         */
        post: operations["upload_month_api_v1_ingestion_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingestion/batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Batches */
        get: operations["list_batches_api_v1_ingestion_batches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingestion/batches/{batch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Batch */
        get: operations["get_batch_api_v1_ingestion_batches__batch_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Summary
         * @description KPIs: volumes, suspicious rate, average score, bands, USD at risk and review counts.
         */
        get: operations["summary_api_v1_analytics_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/risk-distribution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Risk Distribution */
        get: operations["risk_distribution_api_v1_analytics_risk_distribution_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/trends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trends */
        get: operations["trends_api_v1_analytics_trends_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/breakdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Breakdown */
        get: operations["breakdown_api_v1_analytics_breakdown_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/top-accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Top Accounts
         * @description GL accounts with the most suspicious transactions, then the most USD at stake.
         */
        get: operations["top_accounts_api_v1_analytics_top_accounts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Models */
        get: operations["list_models_api_v1_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Active Model */
        get: operations["active_model_api_v1_models_active_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/{version_id}/evaluation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Evaluation
         * @description Model comparison, champion metrics, curves, confusion matrices and feature importance.
         */
        get: operations["evaluation_api_v1_models__version_id__evaluation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/{version_id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Activate
         * @description Make this version the one that scores new transactions. Takes effect at once.
         */
        post: operations["activate_api_v1_models__version_id__activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync
         * @description Register artifacts added to MODEL_DIR since startup (e.g. after `fraudml train`).
         */
        post: operations["sync_api_v1_models_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reviews/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Queue
         * @description Flagged transactions nobody has reviewed yet, highest priority first.
         */
        get: operations["queue_api_v1_reviews_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Reviews
         * @description Reviews; pending ones come highest priority first.
         */
        get: operations["list_reviews_api_v1_reviews_get"];
        put?: never;
        /**
         * Create Review
         * @description Record a decision on a transaction; it waits for an approver.
         */
        post: operations["create_review_api_v1_reviews_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reviews/{review_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve */
        post: operations["approve_api_v1_reviews__review_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reviews/{review_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject */
        post: operations["reject_api_v1_reviews__review_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reviews/bulk-approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk Approve
         * @description Approve many reviews at once; ones that cannot be approved are listed with the reason.
         */
        post: operations["bulk_approve_api_v1_reviews_bulk_approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export
         * @description Download transactions matching the same filters as GET /transactions, as CSV.
         */
        get: operations["export_api_v1_reports_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Audit
         * @description The audit trail, newest first.
         */
        get: operations["list_audit_api_v1_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApproveRequest */
        ApproveRequest: {
            /**
             * Note
             * @default
             */
            note?: string;
        };
        /** AuditOut */
        AuditOut: {
            /** Id */
            id: number;
            /** User Id */
            user_id: number | null;
            /** Action */
            action: string;
            /** Entity */
            entity: string;
            /** Entity Id */
            entity_id: string | null;
            /** Before */
            before: {
                [key: string]: unknown;
            } | null;
            /** After */
            after: {
                [key: string]: unknown;
            } | null;
            /** Request Id */
            request_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** BandCount */
        BandCount: {
            /** Band */
            band: string;
            /** Count */
            count: number;
            /** Share */
            share: number;
        };
        /** BatchItem */
        BatchItem: {
            /** Index */
            index: number;
            /**
             * Status
             * @enum {string}
             */
            status: "scored" | "error";
            /** Transaction Id */
            transaction_id?: string | null;
            result?: components["schemas"]["ScoreResult"] | null;
            /** Error */
            error?: string | null;
            /** Status Code */
            status_code?: number | null;
        };
        /** BatchOut */
        BatchOut: {
            /** Id */
            id: number;
            /** Period */
            period: string;
            /** Method */
            method: string;
            /** Status */
            status: string;
            /** Files */
            files: {
                [key: string]: unknown;
            };
            /** Records */
            records: {
                [key: string]: unknown;
            };
            /** Summary */
            summary: {
                [key: string]: unknown;
            };
            /** Transactions Loaded */
            transactions_loaded: number;
            /** Transactions Scored */
            transactions_scored: number;
            /** Error */
            error: string | null;
            /** Duration Ms */
            duration_ms: number | null;
            /** Created By Id */
            created_by_id: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
        };
        /** BatchPredictionRequest */
        BatchPredictionRequest: {
            /** Transactions */
            transactions: components["schemas"]["PredictionRequest"][];
        };
        /** BatchPredictionResult */
        BatchPredictionResult: {
            /** Scored */
            scored: number;
            /** Failed */
            failed: number;
            /** Items */
            items: components["schemas"]["BatchItem"][];
        };
        /** Body_login_api_v1_auth_login_post */
        Body_login_api_v1_auth_login_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope?: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /** Body_start_session_api_v1_auth_session_post */
        Body_start_session_api_v1_auth_session_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope?: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /** Body_upload_month_api_v1_ingestion_upload_post */
        Body_upload_month_api_v1_ingestion_upload_post: {
            /**
             * Period
             * @example 202608
             */
            period: string;
            /**
             * Gl
             * @description GL report (.xml)
             */
            gl: string;
            /**
             * Fa
             * @description FA report (.csv)
             */
            fa: string;
            /**
             * Join Map
             * @description Join map (.txt or .csv)
             */
            join_map: string;
            /**
             * Ma
             * @description MA server script (.py) or export (.csv, .json)
             */
            ma?: string | null;
            /**
             * Ma Url
             * @description Pull MA from its REST API instead of a file
             */
            ma_url?: string | null;
        };
        /** BreakdownRow */
        BreakdownRow: {
            /** Key */
            key: string | null;
            /** Transactions */
            transactions: number;
            /** Suspicious */
            suspicious: number;
            /** Suspicious Rate */
            suspicious_rate: number;
            /** Avg Risk Score */
            avg_risk_score: number | null;
            /** High Or Critical */
            high_or_critical: number;
            /** Exposure Usd */
            exposure_usd: number;
        };
        /** BulkApproveRequest */
        BulkApproveRequest: {
            /** Review Ids */
            review_ids: number[];
            /**
             * Note
             * @default
             */
            note?: string;
        };
        /** BulkApproveResult */
        BulkApproveResult: {
            /** Approved */
            approved: number[];
            /** Skipped */
            skipped: components["schemas"]["SkippedReview"][];
        };
        /** Factor */
        Factor: {
            /** Reason */
            reason: string;
            /** Features */
            features: string[];
            /** Contribution */
            contribution: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ModelEvaluation */
        ModelEvaluation: {
            /** Id */
            id: number;
            /** Version */
            version: string;
            /** Algorithm */
            algorithm: string;
            /** Is Active */
            is_active: boolean;
            /** Test Period */
            test_period: string;
            /** Champion */
            champion: {
                [key: string]: unknown;
            };
            /** Comparison */
            comparison: {
                [key: string]: unknown;
            }[];
            /** Rule Floors */
            rule_floors: {
                [key: string]: number;
            };
            /** Bands */
            bands: unknown[];
            /** Evaluation */
            evaluation: {
                [key: string]: unknown;
            } | null;
        };
        /** ModelVersionOut */
        ModelVersionOut: {
            /** Id */
            id: number;
            /** Version */
            version: string;
            /** Algorithm */
            algorithm: string;
            /** Is Active */
            is_active: boolean;
            /** Threshold */
            threshold: number;
            /** Metrics */
            metrics: {
                [key: string]: unknown;
            };
            /** Train Periods */
            train_periods: string[];
            /** Test Period */
            test_period: string;
            /** Features */
            features: string[];
            /** Trained At */
            trained_at: string | null;
            /**
             * Registered At
             * Format: date-time
             */
            registered_at: string;
            /** N Features */
            readonly n_features: number;
        };
        /** Page[AuditOut] */
        Page_AuditOut_: {
            /** Items */
            items: components["schemas"]["AuditOut"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** Page[BatchOut] */
        Page_BatchOut_: {
            /** Items */
            items: components["schemas"]["BatchOut"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** Page[ReviewOut] */
        Page_ReviewOut_: {
            /** Items */
            items: components["schemas"]["ReviewOut"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** Page[TransactionSummary] */
        Page_TransactionSummary_: {
            /** Items */
            items: components["schemas"]["TransactionSummary"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** PredictionOut */
        PredictionOut: {
            /** Id */
            id: number;
            /** Transaction Id */
            transaction_id: string;
            /** Model Version */
            model_version: string;
            /** Probability */
            probability: number;
            /** Model Score */
            model_score: number;
            /** Risk Score */
            risk_score: number;
            /**
             * Risk Band
             * @enum {string}
             */
            risk_band: "low" | "medium" | "high" | "critical";
            /** Priority */
            priority: number;
            /** Exposure Usd */
            exposure_usd: number;
            /** Break Types */
            break_types: string[];
            /** Rule Hits */
            rule_hits: components["schemas"]["RuleHit"][];
            /** Top Factors */
            top_factors: components["schemas"]["Factor"][];
            /** Source */
            source: string;
            /** Latency Ms */
            latency_ms: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** PredictionRequest */
        PredictionRequest: {
            /**
             * Account Key
             * @example ACC0001
             */
            account_key: string;
            /**
             * Transaction Date
             * Format: date
             */
            transaction_date: string;
            /**
             * Amount
             * @example 1250
             */
            amount: number;
            /**
             * Currency
             * @example USD
             */
            currency: string;
            /**
             * Country
             * @example US
             */
            country: string;
            /**
             * Description
             * @example Vendor payment
             */
            description: string;
            /**
             * Transaction Id
             * @description Generated (16 hex characters) when left out.
             * @example 9F3A5C7E1B2D4F60
             */
            transaction_id?: string | null;
            /**
             * Source System
             * @default gl
             * @enum {string}
             */
            source_system?: "gl" | "ma" | "fa";
            /**
             * Counterparts
             * @description The same transaction as recorded by the other systems, when known.
             */
            counterparts?: {
                [key: string]: components["schemas"]["RecordIn"];
            };
        };
        /**
         * RecordIn
         * @description One system's record of a transaction. Business rules (ID and account formats, supported
         *     currencies and countries, amount range) are checked by the rule engine and reported as
         *     rule_violation breaks, not rejected here.
         */
        RecordIn: {
            /**
             * Account Key
             * @example ACC0001
             */
            account_key: string;
            /**
             * Transaction Date
             * Format: date
             */
            transaction_date: string;
            /**
             * Amount
             * @example 1250
             */
            amount: number;
            /**
             * Currency
             * @example USD
             */
            currency: string;
            /**
             * Country
             * @example US
             */
            country: string;
            /**
             * Description
             * @example Vendor payment
             */
            description: string;
        };
        /** RejectRequest */
        RejectRequest: {
            /**
             * Note
             * @description Why the decision is rejected.
             */
            note: string;
        };
        /** ReviewCreate */
        ReviewCreate: {
            /** Transaction Id */
            transaction_id: string;
            /**
             * Decision
             * @enum {string}
             */
            decision: "confirmed" | "false_positive";
            /**
             * Note
             * @default
             */
            note?: string;
        };
        /** ReviewOut */
        ReviewOut: {
            /** Id */
            id: number;
            /** Transaction Id */
            transaction_id: string;
            /** Prediction Id */
            prediction_id: number | null;
            /**
             * Decision
             * @enum {string}
             */
            decision: "confirmed" | "false_positive";
            /** Note */
            note: string;
            /** Status */
            status: string;
            /** Analyst Id */
            analyst_id: number;
            /** Analyst Email */
            analyst_email: string;
            /** Approver Id */
            approver_id: number | null;
            /** Approver Email */
            approver_email: string | null;
            /** Approver Note */
            approver_note: string | null;
            /** Decided At */
            decided_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** RiskDistribution */
        RiskDistribution: {
            /** Period */
            period: string | null;
            /** Bins */
            bins: components["schemas"]["ScoreBin"][];
            /** Bands */
            bands: components["schemas"]["BandCount"][];
        };
        /** RuleHit */
        RuleHit: {
            /** Break Type */
            break_type: string;
            /** Reason */
            reason: string;
        };
        /** ScoreBin */
        ScoreBin: {
            /** Score From */
            score_from: number;
            /** Score To */
            score_to: number;
            /** Count */
            count: number;
        };
        /** ScoreResult */
        ScoreResult: {
            /** Id */
            id: number;
            /** Transaction Id */
            transaction_id: string;
            /** Model Version */
            model_version: string;
            /** Probability */
            probability: number;
            /** Model Score */
            model_score: number;
            /** Risk Score */
            risk_score: number;
            /**
             * Risk Band
             * @enum {string}
             */
            risk_band: "low" | "medium" | "high" | "critical";
            /** Priority */
            priority: number;
            /** Exposure Usd */
            exposure_usd: number;
            /** Break Types */
            break_types: string[];
            /** Rule Hits */
            rule_hits: components["schemas"]["RuleHit"][];
            /** Top Factors */
            top_factors: components["schemas"]["Factor"][];
            /** Source */
            source: string;
            /** Latency Ms */
            latency_ms: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Created
             * @description False when the record was added to a known transaction.
             */
            created: boolean;
            /** In Systems */
            in_systems: ("gl" | "ma" | "fa")[];
        };
        /** SessionOut */
        SessionOut: {
            user: components["schemas"]["UserOut"];
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** SkippedReview */
        SkippedReview: {
            /** Id */
            id: number;
            /** Reason */
            reason: string;
        };
        /** Summary */
        Summary: {
            /** Period */
            period: string | null;
            /** Periods */
            periods: string[];
            /** Transactions */
            transactions: number;
            /** Suspicious */
            suspicious: number;
            /** Suspicious Rate */
            suspicious_rate: number;
            /** Scored */
            scored: number;
            /** Avg Risk Score */
            avg_risk_score: number | null;
            /** High Or Critical */
            high_or_critical: number;
            /** Exposure Usd At Risk */
            exposure_usd_at_risk: number;
            /** By Band */
            by_band: {
                [key: string]: number;
            };
            /** Review Queue */
            review_queue: number;
            /** Pending Approval */
            pending_approval: number;
            /** Confirmed */
            confirmed: number;
            /** False Positive */
            false_positive: number;
        };
        /** SystemRecordOut */
        SystemRecordOut: {
            /** Account Key */
            account_key: string | null;
            /** Transaction Date */
            transaction_date: string | null;
            /** Amount */
            amount: number | null;
            /** Currency */
            currency: string | null;
            /** Country */
            country: string | null;
            /** Description */
            description: string | null;
            /** Rule Violations */
            rule_violations: string[] | null;
        };
        /** Token */
        Token: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type?: string;
            /** Expires In */
            expires_in: number;
            user: components["schemas"]["UserOut"];
        };
        /** TopAccount */
        TopAccount: {
            /** Account */
            account: string;
            /** Transactions */
            transactions: number;
            /** Suspicious */
            suspicious: number;
            /** Max Risk Score */
            max_risk_score: number | null;
            /** Exposure Usd */
            exposure_usd: number;
            /** Last Transaction Date */
            last_transaction_date: string | null;
        };
        /** TransactionDetail */
        TransactionDetail: {
            /** Transaction Id */
            transaction_id: string;
            /** Period */
            period: string;
            /** Gl Account Id */
            gl_account_id: string | null;
            /** Transaction Date */
            transaction_date: string | null;
            /** Amount */
            amount: number | null;
            /** Currency */
            currency: string | null;
            /** Country */
            country: string | null;
            /** Description */
            description: string | null;
            /** In Gl */
            in_gl: boolean;
            /** In Ma */
            in_ma: boolean;
            /** In Fa */
            in_fa: boolean;
            /** Break Types */
            break_types: string[];
            /** Is Suspicious */
            is_suspicious: boolean;
            /** Risk Score */
            risk_score: number | null;
            /** Risk Band */
            risk_band: string | null;
            /** Priority */
            priority: number | null;
            /** Exposure Usd */
            exposure_usd: number | null;
            /** Model Version */
            model_version: string | null;
            /** Scored At */
            scored_at: string | null;
            /** Review Outcome */
            review_outcome: string | null;
            /** Source */
            source: string;
            /** Systems */
            systems: {
                [key: string]: components["schemas"]["SystemRecordOut"] | null;
            };
            /** Expected Ma Key */
            expected_ma_key: string | null;
            /** Expected Fa Key */
            expected_fa_key: string | null;
            /** Gl Account Mapped */
            gl_account_mapped: boolean;
            /** Predictions */
            predictions: components["schemas"]["PredictionOut"][];
            /** Reviews */
            reviews: components["schemas"]["ReviewOut"][];
        };
        /** TransactionSummary */
        TransactionSummary: {
            /** Transaction Id */
            transaction_id: string;
            /** Period */
            period: string;
            /** Gl Account Id */
            gl_account_id: string | null;
            /** Transaction Date */
            transaction_date: string | null;
            /** Amount */
            amount: number | null;
            /** Currency */
            currency: string | null;
            /** Country */
            country: string | null;
            /** Description */
            description: string | null;
            /** In Gl */
            in_gl: boolean;
            /** In Ma */
            in_ma: boolean;
            /** In Fa */
            in_fa: boolean;
            /** Break Types */
            break_types: string[];
            /** Is Suspicious */
            is_suspicious: boolean;
            /** Risk Score */
            risk_score: number | null;
            /** Risk Band */
            risk_band: string | null;
            /** Priority */
            priority: number | null;
            /** Exposure Usd */
            exposure_usd: number | null;
            /** Model Version */
            model_version: string | null;
            /** Scored At */
            scored_at: string | null;
            /** Review Outcome */
            review_outcome: string | null;
            /** Source */
            source: string;
        };
        /** TrendPoint */
        TrendPoint: {
            /** Bucket */
            bucket: string;
            /** Transactions */
            transactions: number;
            /** Suspicious */
            suspicious: number;
            /** Suspicious Rate */
            suspicious_rate: number;
            /** Avg Risk Score */
            avg_risk_score: number | null;
            /** High Or Critical */
            high_or_critical: number;
        };
        /** UserCreate */
        UserCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Full Name
             * @default
             */
            full_name?: string;
            /** Password */
            password: string;
            /**
             * Role
             * @enum {string}
             */
            role: "analyst" | "approver" | "admin";
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** Full Name */
            full_name: string;
            /**
             * Role
             * @enum {string}
             */
            role: "analyst" | "approver" | "admin";
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** UserUpdate */
        UserUpdate: {
            /** Full Name */
            full_name?: string | null;
            /** Password */
            password?: string | null;
            /** Role */
            role?: ("analyst" | "approver" | "admin") | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    ready_api_v1_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_api_v1_auth_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    current_session_api_v1_auth_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
        };
    };
    start_session_api_v1_auth_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_start_session_api_v1_auth_session_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    end_session_api_v1_auth_session_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    list_users_api_v1_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"][];
                };
            };
        };
    };
    create_user_api_v1_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_api_v1_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    score_transaction_api_v1_predictions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PredictionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    score_batch_api_v1_predictions_batch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchPredictionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchPredictionResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_prediction_api_v1_predictions__prediction_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                prediction_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_transactions_api_v1_transactions_get: {
        parameters: {
            query?: {
                sort?: string;
                page?: number;
                page_size?: number;
                period?: string | null;
                band?: ("low" | "medium" | "high" | "critical")[] | null;
                min_score?: number | null;
                max_score?: number | null;
                break_type?: string | null;
                suspicious?: boolean | null;
                currency?: string | null;
                country?: string | null;
                account?: string | null;
                date_from?: string | null;
                date_to?: string | null;
                search?: string | null;
                reviewed?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_TransactionSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_transaction_api_v1_transactions__transaction_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_month_api_v1_ingestion_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_month_api_v1_ingestion_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_batches_api_v1_ingestion_batches_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_BatchOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_batch_api_v1_ingestion_batches__batch_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    summary_api_v1_analytics_summary_get: {
        parameters: {
            query?: {
                /** @description YYYYMM; all if omitted */
                period?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Summary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    risk_distribution_api_v1_analytics_risk_distribution_get: {
        parameters: {
            query?: {
                /** @description YYYYMM; all if omitted */
                period?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskDistribution"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trends_api_v1_analytics_trends_get: {
        parameters: {
            query?: {
                granularity?: "day" | "month";
                /** @description YYYYMM; all if omitted */
                period?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrendPoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    breakdown_api_v1_analytics_breakdown_get: {
        parameters: {
            query: {
                by: "currency" | "country" | "description" | "period" | "band" | "break_type";
                /** @description YYYYMM; all if omitted */
                period?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BreakdownRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    top_accounts_api_v1_analytics_top_accounts_get: {
        parameters: {
            query?: {
                /** @description YYYYMM; all if omitted */
                period?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopAccount"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_models_api_v1_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelVersionOut"][];
                };
            };
        };
    };
    active_model_api_v1_models_active_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelVersionOut"];
                };
            };
        };
    };
    evaluation_api_v1_models__version_id__evaluation_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelEvaluation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activate_api_v1_models__version_id__activate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelVersionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_api_v1_models_sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelVersionOut"][];
                };
            };
        };
    };
    queue_api_v1_reviews_queue_get: {
        parameters: {
            query?: {
                min_score?: number | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_TransactionSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_reviews_api_v1_reviews_get: {
        parameters: {
            query?: {
                status?: ("pending" | "approved" | "rejected") | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ReviewOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_review_api_v1_reviews_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_api_v1_reviews__review_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_api_v1_reviews__review_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_approve_api_v1_reviews_bulk_approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkApproveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkApproveResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_api_v1_reports_export_get: {
        parameters: {
            query?: {
                format?: "csv";
                period?: string | null;
                band?: ("low" | "medium" | "high" | "critical")[] | null;
                min_score?: number | null;
                max_score?: number | null;
                break_type?: string | null;
                suspicious?: boolean | null;
                currency?: string | null;
                country?: string | null;
                account?: string | null;
                date_from?: string | null;
                date_to?: string | null;
                search?: string | null;
                reviewed?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_audit_api_v1_audit_get: {
        parameters: {
            query?: {
                entity?: string | null;
                entity_id?: string | null;
                action?: string | null;
                user_id?: number | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_AuditOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
